タスク管理アプリ途中
terry-man-com/learning_plan pull request #1
Opened 2022-05-22 04:31 UTC by terry-man-com

### カリキュラムURL

### 課題番号
タスク管理アプリ

### 現在の状況
ブレークポイントのところがうまくいきません。PHP の部分はどうにか課題の要件を満たせていると思うのですが😅
一度コードを見ていただきたいので、よろしくお願いします！

### 期待していた動作

### 調べたこと・参考にしたURL

2022-05-22 05:55 UTC, kazu-taka commented
@terry-man-com 
次回から、うまくいかない(正しく表示されない)場合は、そのスクリーンショットを貼ってもらえると助かります✨

2022-05-22 06:02 UTC, kazu-taka commented
@terry-man-com 
今回の質問と関係ないですが、何かが残ってます^^;
![image](https://user-images.githubusercontent.com/5278718/169681200-90c4253e-8a88-4de1-86bf-ea210a487639.png)

2022-05-22 07:39 UTC, kazu-taka requested changes
@terry-man-com 
まだ完璧まではいかないと思いますが、ある程度完成に近づくと思うので確認お願いします😊

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 89%;
@terry-man-com 
`plan-list`と`table`は同じものになるので、なるべくclassで指定するようにして下さい✨
他のページでもtableを使用した際に、そちらのデザインまで崩れる可能性があります^^;
また、`plan-list`で`margin: 10px 50px;`を指定しているので、widthの指定は不要です😊

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    margin-left: 45px;
@terry-man-com 
margin-leftで調整せずに、formのpaddingで調整した方がよいです✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 90%;
@terry-man-com 
widthは100%にして、`.form-area`のpaddingで余白を調整して下さい✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    margin-left: 45px;
@terry-man-com 
`margin-left`は削除して`.form-area`のpaddingで余白を調整して下さい✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    margin-left: 45px;
@terry-man-com 
こちらのmargin-leftも削除して`.form-area`のpaddingで余白を調整して下さい✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +.delete-link-are {
@terry-man-com 
`delete-link-area`の`area` が`are`になってます^^;

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 90%;
@terry-man-com 
横まで広げたいので、widthは削除してOKです！！

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 90%;
@terry-man-com 
ここも横まで広げたいので削除してOKです✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 90%;
@terry-man-com 
横まで広げたいので削除してOKです✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 90%;
@terry-man-com 
横まで広げたいので削除してOKです✨

2022-05-22 07:39 UTC, kazu-taka commented on style.css
> +    width: 55%;
@terry-man-com 
もう少しタイトルの幅を狭めたほうがいいと思います✨

2022-05-24 05:25 UTC, terry-man-com commented on style.css
> +    width: 55%;
添削ありがとうございました！

2022-05-24 14:03 UTC, kazu-taka requested changes
@terry-man-com 
コメントしたので確認お願いします✨

2022-05-24 14:03 UTC, kazu-taka commented on style.css
> +        width: 300px;
@terry-man-com 
600pxで切り替えているので、widthは500pxくらいまで広げてあがた方がいいと思います✨

2022-05-24 14:03 UTC, kazu-taka commented on style.css
> +    padding: 40px 50px;
@terry-man-com 
タブレットとスマホサイズの時は、paddingの左右の50pxは無くしてもいいと思います✨

2022-05-24 14:03 UTC, kazu-taka commented on style.css
> +    width: 10%;
@terry-man-com 
スマホサイズの時にボタンが折り返してしまうので、もう少し広げた方がいいと思います✨

2022-05-24 14:03 UTC, kazu-taka commented on style.css
> +    width: 10%;
@terry-man-com 
完了期限と3つのボタンについては、幅は固定にして(折り返さないサイズ)、`plan-title`を可変するのがいいと思います！完了期限と3つのボタンのwidthを固定にして、`plan-title`のwidthを削除すると、`plan-title`が可変になります✨

2022-05-25 14:43 UTC, terry-man-com commented
添削ありがとうございました！
ご指摘いただいた`plan-title`を可変にして他を固定するやり方で他の部分も直して、カリキュラムの見本に近づくように修正しました。どうかチェックよろしくお願いします！

2022-05-25 21:10 UTC, kazu-taka commented on style.css
> +        padding: 20px;
@terry-man-com 
スマホサイズの時は左右のpaddingはなくてもいいので、`padding: 20px 0`とかでもいいと思います✨

2022-05-25 21:11 UTC, kazu-taka commented
@terry-man-com 
1箇所修正したら、マージしてOKです👍
(マージ前にプルリクのDraftを変更)
![LGTM](https://image.lgtmoon.dev/167484)

2022-05-26 01:51 UTC, kazu-taka requested changes

2022-05-26 01:51 UTC, kazu-taka commented on delete.php
> +?>
@terry-man-com 
PHPのコードで終わる時は閉じタグが不用です👍

2022-05-26 01:51 UTC, kazu-taka commented on done_cancel.php
> +?>
@terry-man-com 
こちらも閉じタグ不用です👍

2022-05-26 02:16 UTC, terry-man-com commented
添削ありがとうございました！
ご指摘いただいた部分を修正したのでチェックお願いします！

2022-05-26 02:45 UTC, kazu-taka commented
@terry-man-com 
私が見逃していた部分の修正もありがとうございます✨
マージしてOKです！！

2022-05-26 03:25 UTC, terry-man-com commented
ありがとうございました！
マージいたします！

2022-05-26 03:27 UTC, merged